### ISSUE TITLE
Questions about this project

### ISSUE THREAD

**Issue by visortelle** [agolovenko/avro-tools#6]
Hi! 👋
I have two questions:

- **Question 1** Regarding AVRO <---> JSON conversion, what are the major differences with this project if any?

  https://github.com/allegro/json-avro-converter

- **Question 2** How do you think this project is still relevant in the sense of supporting the newest AVRO versions?

Thank you.

**Comment by agolovenko** [comment]
Hi @visortelle, thanks for asking.
1. Both projects are similar. The other one is implemented in Java and not supported ATM. This one is in Scala and you can expect a bug fix from me. Also there're number of outstanding features:
- Supported input formats: json, csv, xml
- Pluggable StringParsers
- Pluggable validations
- Renaming of fields that aren't named within avro convention: [A-Za-z0-9_]
- Descriptive errors that include path of origin

2. Unless there's some breaking change in AVRO there should be no problems supporting a newer version

**Comment by visortelle** [comment]
@agolovenko 👍 I'm satisfied with both answers.

Thank you for your work!

~~I wonder why the "user-friendly" JSON encoding is still not supported in the official AVRO library.~~
